version: "3.9"

services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  listener:
    build: .
    container_name: hl7-listener
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "2575:2575"
    command: python3 -m app.listener
    restart: unless-stopped